blog/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^(?P<slug>[-_\w]+)/$', views.post_single, name = 'post_single'),
    url(r'^category/(?P<slug>[-_\w]+)/$', views.posts_cat, name = 'posts_cat'),
    url(r'^$', views.index, name='index'),
]

portfolio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^markdown/', include('django_markdown.urls')),
    url(r'^blog/',include('blog.urls', namespace="blog")),
    url(r'^', include('resume.urls', namespace="resume")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', views.about, name='about'),
    url(r'^projects/$', views.index, name='index'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^contact/thanks/$',views.contact_thanks,name='contact_thanks'),

]

blog/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.utils import timezone
from django.template.defaultfilters import slugify
from django_markdown.models import MarkdownField


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/categories/%s/" % self.slug

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        return super(Category,self).save(*args, **kwargs)


class Post(models.Model):

    author = models.ForeignKey(User,limit_choices_to={'is_staff': True})
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=200, unique=True)
    photo = models.ImageField(upload_to='blog/posts',blank=True)
    thumbnail = models.ImageField(upload_to='blog/posts',blank=True)
    content = MarkdownField()
    summary = models.TextField()
    updatedAt =  models.DateTimeField('date modified',auto_now=True)
    createdAt =  models.DateTimeField('date published',auto_now_add=True)
    category = models.ManyToManyField(Category)

    class Meta:
	    verbose_name_plural = "Posts"

    def __str__(self):
        return self.title

    def save(self,*args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        return super(Post,self).save(*args, **kwargs)

    def next(self):
        try:
            return get_object_or_404(Post,pk=self.pk+1)
        except:
            return None

    def previous(self):
        try :
            return get_object_or_404(Post,pk=self.pk-1)
        except:
            return None

resume/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.template.defaultfilters import slugify
from django_markdown.models import MarkdownField


class Skill(models.Model):

	title = models.CharField(max_length=250)
	logo = models.ImageField(upload_to='resume/skills',blank=True)
	term = models.CharField(max_length=100)
	slug = models.SlugField(max_length=100, unique=True)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.title)
		return super(Skill,self).save(*args, **kwargs)

class Project(models.Model):

    title = models.CharField(max_length=300)
    description = MarkdownField()
    github_link = models.URLField(max_length=300,blank=True)
    android = models.URLField(max_length=300,blank=True)
    ios = models.URLField(max_length=300,blank=True)
    web = models.URLField(max_length=300,blank = True)
    skills  = models.ManyToManyField(Skill)
    author = models.ForeignKey(User,limit_choices_to={'is_staff': True})
    image = models.ImageField(upload_to='resume/projects',blank=True)
    slug = models.SlugField(max_length=120, unique=True)
    updatedAt =  models.DateTimeField(auto_now=True)
    createdAt =  models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        return super(Project,self).save(*args, **kwargs)

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Post


def index(request):
    posts = Post.objects.order_by("-createdAt")
    context = {"posts": posts}
    return render(request,'blog/blog.html',context)

def post_single(request,slug):
    post = get_object_or_404(Post,slug=slug)
    context = {"post":post}
    return render(request,'blog/single.html',context)

def posts_cat(request,slug):
    posts = Category.objects.get(slug=slug).post_set.all()
    context = {"posts": posts}
    return render(request,'blog/blog.html',context)

resume/views.py
from django.shortcuts import render,get_object_or_404
from .models import Skill,Project
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
import json

def index(request):
        projects = Project.objects.order_by('createdAt')
        context = {"projects":projects}
        return render(request,'resume/index.html', context)

def about(request):
    context = ''
    return render(request,'resume/about.html',context)

def contact_thanks(request):
    context = ''
    return render(request,'resume/contact_thanks.html',context)

def contact(request):
    if request.method == "POST":
        full_name = request.POST.get('full_name', '')
        note = request.POST.get('note', '')
        from_email = request.POST.get('email', '')
        subject = 'Get in touch - portfolio website'
        if subject and note and from_email and full_name:
            try:
                note += "\n From: " + full_name + "\n Email: " + from_email
                print(note)
                send_mail(subject, note, from_email, ['hassanabidpk89@gmail.com'])
            except BadHeaderError:
                print("invalid header")
                return HttpResponse(json.dumps({'message':'Invalid header found.'}),content_type="application/json")
            return HttpResponse(json.dumps({'message':'Thanks for getting in touch! I will get back to you ASAP!'}),content_type="application/json")
        else:
            return HttpResponse(json.dumps({'message':"Fill in all the fields and try again!"}),content_type="application/json")
    else:
        context = {}
        return render(request,'resume/contact.html',context)

blog/templates/blog/blog.html
{% extends 'resume/base.html' %}
{% load staticfiles %}
{% load django_markdown %}
{% load humanize %}
{% block title %}
<title>Hassan Abid - Blog</title>
{% endblock %}
{% block fbtags %}
<!-- Fb Tags-->
<meta name="description" content="Hassan is a passionate Software Engineer with several years of experience in
Android,iOS and Web development. He is currently based in Seoul.When he’s not coding, he can be found hiking, running or
cycling with his smart watch to record all his outdoor activities.">
  <meta property="og:type" content="article" />
  <meta property="og:locale" content="en_US" />
  <meta property="og:title" content="Hassan Abid" />
  <meta property="fb:app_id" content="722253317920977" />
  <meta property="article:author" content="https://www.facebook.com/hassanabidpk89" />
  <meta property="og:description" content="Hassan is a passionate Software Engineer with several years of experience in
  Android,iOS and Web development. He is currently based in Seoul.When he’s not coding, he can be found hiking, running or
  cycling with his smart watch to record all his outdoor activities." />
  <meta property="og:image"content="http://www.hassanabid.com/static/resume/images/hassan_gds.jpg" />
  <meta property="og:url" content="http://hassanabid.com/blog" />
{% endblock %}
{% block blog-active %} is-active {% endblock %}
{% block fbjs %}
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '722253317920977',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
{% endblock %}
{% block content %}
<div class="mdl-grid portfolio-max-width">
  {% if posts %}
  {% for post in posts %}
  {% if forloop.first %}
    <div class="mdl-grid mdl-cell mdl-cell--12-col mdl-cell--4-col-tablet mdl-card mdl-shadow--4dp">
      {% if post.photo %}
        <div class="mdl-card__media mdl-cell mdl-cell--12-col-tablet">
            <a href="{% url 'blog:post_single' post.slug %}"><img class="article-image-first" src="{{ post.photo.url }}" border="0" alt=""></a>
        </div>
        {% endif %}
        <div class="mdl-cell mdl-cell--12-col">
            <h2 class="mdl-card__title-text">{{ post.title }}</h2>
            <div class="mdl-card__supporting-text padding-top">
                <span>Posted {{ post.createdAt|naturaltime }}</span>
                <a href="" onclick="fbshare('{{ post.slug }}',{% if post.photo %} '{{ post.photo.url }}' {% else %} '' {% endif %},
                '{{ post.title }}','{{ post.summary }}')"><div id="tt2" class=" icon material-icons portfolio-share-btn">share</div></a>
                <div class="mdl-tooltip" for="tt1">
                    Share via social media
                </div>
            </div>
            <div class="mdl-card__supporting-text no-left-padding">
                <p>{{ post.summary }}</p>
                <span>Category:
                {% for cat in post.category.all %}
                  <a href="{% url 'blog:posts_cat' cat.slug %}">{{ cat.title }}</a>
                {% endfor %}
                </span>
            </div>
            <div class="mdl-card__actions mdl-card--border">
              <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="{% url 'blog:post_single' post.slug %}">
                Read More
              </a>
            </div>
        </div>
    </div>
    {% else %}
    <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet mdl-card mdl-shadow--4dp">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">{{ post.title }}</h2>
        </div>
        {% if post.thumbnail %}
        <div class="mdl-card__media">
            <a href="{% url 'blog:post_single' post.slug %}"> <img class="article-image" src="{{ post.thumbnail.url }}" border="0" alt=""></a>
        </div>
        {% endif %}
        <div class="mdl-card__supporting-text no-bottom-padding">
            <span>{{ post.createdAt|naturaltime }}</span>
            <a href="" onclick="fbshare('{{ post.slug }}',{% if post.photo %}'{{ post.photo.url }}' {% else %} '' {% endif %},
            '{{ post.title }}','{{ post.summary }}')"><div id="tt2" class=" icon material-icons portfolio-share-btn">share</div></a>
            <div class="mdl-tooltip" for="tt2">
                Share via social media
            </div>
        </div>
        <div class="mdl-card__supporting-text">
            <p>{{ post.summary }}</p>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-button--accent" href="{% url 'blog:post_single' post.slug %}">
            Read More
          </a>
        </div>
    </div>
    {% endif %}
    {% endfor %}
    {% else %}
    <h3>No posts added yet</h3>
    {% endif %}
</div>
{% endblock %}
{% block fbshare %}
<script>
function fbshare(slug,photo,title){
  var blogUrl = 'http://www.hassanabid.com/blog/';
  var baseUrl = 'http://www.hassanabid.com';
    FB.ui({
      method: 'share',
      href: blogUrl.concat(slug),
      picture: baseUrl.concat(photo),
      caption: title,
      summary: summary,
    }, function(response){
      if (response && !response.error_message) {
      console.log('Posting completed.');
      } else {
        console.log('Error while posting.');
      }
    });
}
</script>
{% endblock %}

blog/templates/blog/single.html
{% extends 'resume/base.html' %}
{% load staticfiles %}
{% load django_markdown %}
{% load humanize %}
{% block title %}
<title>{{ post.title }}</title>
{% endblock %}
{% block fbtags %}
<!-- Fb Tags-->
<meta name="description" content="{{ post.summary }}">
  <meta property="og:type" content="article" />
  <meta property="og:locale" content="en_US" />
  <meta property="og:title" content="{{ post.title }}" />
  <meta property="fb:app_id" content="722253317920977" /> 
  <meta property="article:author" content="https://www.facebook.com/hassanabidpk89" />
  <meta property="og:description" content="{{ post.summary }}" />
  {% if post.photo %}
  <meta property="og:image"content="http://www.hassanabid.com{{ post.photo.url }}" />
  {% else %}
  <meta property="og:image"content="http://www.hassanabid.com/static/resume/images/hassan_gds.jpg" />
  {% endif %}
  <meta property="og:url" content="http://www.hassanabid.com/blog/{{ post.slug }}" />
{% endblock %}
{% block fbjs %}
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '722253317920977',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
{% endblock %}
{% block content %}
<div class="mdl-grid portfolio-max-width">
    <div class="mdl-cell mdl-cell--12-col mdl-card mdl-shadow--4dp">
        {% if post.photo %}
        <div class="mdl-card__media">
            <img class="article-image" src="{{ post.photo.url }}" border="0" alt="">
        </div>
        {% endif %}
        <div class="mdl-card__supporting-text">
          Category:
            {% for cat in post.category.all %}
            <a href="{% url 'blog:posts_cat' cat.slug %}">{{ cat.title }}</a>
            {% endfor %}
            <a href="" onclick="fbshare('{{ post.slug }}',{% if post.photo %}'{{ post.photo.url }}' {% else %} ''{% endif %},'{{ post.title }}')"><div id="tt2" class=" icon material-icons portfolio-share-btn">share</div></a>
        </div>
            <h3 class="mdl-cell mdl-cell--12-col-desktop mdl-cell--4-col-phone mdl-typography--headline">{{ post.title }}</h3>
            <div class="mdl-cell mdl-cell--12-col mdl-card__supporting-text no-padding">
                <p>
                    {{ post.content|markdown }}
                </p>
            </div>
        <div class="mdl-card__supporting-text">
          <span>{{ post.createdAt|naturaltime }}</span>
        </div>
    </div>
</div>
{% endblock %}
{% block fbshare %}
<script>
function fbshare(){
    FB.ui({
      method: 'share',
      href: 'http://www.hassanabid.com/blog/{{ post.slug }}',
      {% if post.photo %}
      picture: 'http://hassanabid.com{{ post.photo.url }}', {% endif %}
      caption: '{{ post.title }}',
      summary: "{{ post.summary }}",

    }, function(response){
      if (response && !response.error_message) {
      console.log('Posting completed.');
      } else {
        console.log('Error while posting.');
      }
    });
}
</script>
{% endblock %}

resume/templates/resume/about.html
{% extends 'resume/base.html' %}
{% load staticfiles %}
{% load django_markdown %}
{% block title %}
<title>Hassan Abid</title>
{% endblock %}
{% block fbtags %}
<!-- Fb Tags-->
<meta name="description" content="Hassan is a passionate Software Engineer with several years of experience in
Android,iOS and Web development. He is currently based in Seoul.When he’s not coding, he can be found hiking, running or
cycling with his smart watch to record all his outdoor activities.">
  <meta property="og:type" content="article" />
  <meta property="og:locale" content="en_US" />
  <meta property="og:title" content="Hassan Abid" />
  <meta property="article:author" content="https://www.facebook.com/hassanabidpk89" />
  <meta property="og:description" content="Hassan is a passionate Software Engineer with several years of experience in
  Android,iOS and Web development. He is currently based in Seoul.When he’s not coding, he can be found hiking, running or
  cycling with his smart watch to record all his outdoor activities." />
  <meta property="og:image"content="http://www.hassanabid.com/static/resume/images/hassan_gds.jpg" />
  <meta property="og:url" content="http://hassanabid.com/about/" />
{% endblock %}
{% block about-active %} is-active {% endblock %}
{% block content %}
<div class="mdl-grid portfolio-max-width">

    <div class="mdl-cell mdl-cell--12-col mdl-card mdl-shadow--4dp">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">About</h2>
        </div>
        <div class="mdl-card__media">
            <img class="article-image" src="{% static 'resume/images/about-header.jpg' %}" border="0" alt="">
        </div>

        <div class="mdl-grid portfolio-copy">
            <h3 class="mdl-cell mdl-cell--12-col mdl-typography--headline">Introduction</h3>
            <div class="mdl-cell mdl-cell--12-col mdl-card__supporting-text no-padding ">
                <p>
                  I'm Hassan Abid a passionate Software Engineer with several years of experience in Android,iOS and web programming. I'm based in Seoul and currently working for NexStreaming Corp.
                  In my free time, I help under-represented people to learn programming. My favorite quote is "Simplicity is the ultimate sophistication". When I am not coding, I go out for hiking, running or cycling.
                </p>
            </div>




            <h3 class="mdl-cell mdl-cell--12-col mdl-typography--headline">Summary</h3>

            <div class="mdl-cell mdl-cell--12-col mdl-card__supporting-text no-padding ">
                <p>
                  I am a meticulous full-stack developer who undertakes assignments with utmost responsibility,
                  meet deadlines, and delivers quality work. I possess practical and up-to-date knowledge about
                  android and iOS SDKs. I apply analytical skills in solving day-to-day problems and challenges.
                  I operate with eagerness and strong sense of urgency. I expertise in Android(3+), iOS(1.5+) and
                  web(2+) along side with strong knowledge of server backends. I posses ability to develop a
                  full-fledge mobile and web app. </p>
                  <p>I have quest for learning. I have completed several online
                  courses and certifications including Android Developers nanodegree(Udacity),
                  iOS development with Swift(Udacity) and Python(MITx).  </p>
                  <p>I have strong experience building and maintaining SDKs. At my current working place(NexStreaming),
                  I maintain Swift demo
                  app for the NexPlayer SDK and from time-to-time fix bugs in NexPlayer iOS SDK. To me
                  learning and exploring new technologies and opportunities have no end. I am looking
                  for a more flexible role where I can apply all my skills related to mobile and web
                  development for launching a complete product off-ground.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

resume/templates/resume/base.html
{% load staticfiles %}
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    {% block title %}
    <title>Hassan Abid</title>
    {% endblock %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.cyan-deep_orange.min.css" />
    <link rel="stylesheet" href="{% static 'resume/css/styles.css' %}" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/styles/default.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <!-- favicons -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'resume/images/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'resume/images/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'resume/images//apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'resume/images/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'resume/images/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'resume/images/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'resume/images/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'resume/images/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'resume/images/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'resume/images/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'resume/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'resume/images/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'resume/images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'resume/images/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'resume/images/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    {% block fbtags %}
    {% endblock %}


</head>

<body>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-32474920-2', 'auto');
  ga('send', 'pageview');

  </script>
  {% block fbjs %}
  {% endblock %}
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header mdl-layout__header--waterfall portfolio-header">
            <div class="mdl-layout__header-row portfolio-logo-row">
                <span class="mdl-layout__title">
                    <div class="portfolio-logo"></div>
                    <span class="mdl-layout__title">Hassan Abid</span>
                </span>
            </div>
            <div class="mdl-layout__header-row portfolio-navigation-row mdl-layout--large-screen-only">
                <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
                  <a class="mdl-navigation__link {% block about-active %} {% endblock %}" href="/">About</a>
                    <a class="mdl-navigation__link {% block port-active %} {% endblock %}" href="/projects/">Projects</a>
                    <a class="mdl-navigation__link {% block blog-active %} {% endblock %}" href="/blog/">Blog</a>
                    <a class="mdl-navigation__link {% block contact-active %} {% endblock %}" href="/contact/">Contact</a>
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer mdl-layout--small-screen-only">
            <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
              <a class="mdl-navigation__link" href="/">About</a>
              <a class="mdl-navigation__link is-active" href="/projects/">Projects</a>
              <a class="mdl-navigation__link" href="/blog/">Blog</a>
              <a class="mdl-navigation__link" href="/contact/">Contact</a>
            </nav>
        </div>
        <main class="mdl-layout__content">
              {% block content %}
              {% endblock %}
            <footer class="mdl-mini-footer">
                <div class="mdl-mini-footer__left-section">
                    <div class="mdl-logo">Built with Django and Material Design Lite</div>
                </div>
                <div class="mdl-mini-footer__right-section">
                    <ul class="mdl-mini-footer__link-list">
                        <li><a href="https://twitter.com/hassanabidpk">Twitter</a></li>
                        <li><a href="https://www.linkedin.com/in/hassanabid89">LinkedIn</a></li>
                        <li><a href="https://github.com/hassanabidpk">Github</a></li>
                    </ul>
                </div>
            </footer>
        </main>
    </div>
    <script src="https://code.getmdl.io/1.1.3/material.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    {% block fbshare %}
    {% endblock %}
    {% block contactjs %}
    {% endblock %}
</body>

</html>

resume/templates/resume/contact.html
{% extends 'resume/base.html' %}
{% load staticfiles %}
{% load django_markdown %}
{% block title %}
<title>Hassan Abid</title>
{% endblock %}
{% block fbtags %}
<!-- Fb Tags-->
<meta name="description" content="Hassan is a passionate Software Engineer with several years of experience in
Android,iOS and Web development. He is currently based in Seoul.When he’s not coding, he can be found hiking, running or
cycling with his smart watch to record all his outdoor activities.">
  <meta property="og:type" content="article" />
  <meta property="og:locale" content="en_US" />
  <meta property="og:title" content="Hassan Abid" />
  <meta property="fb:app_id" content="722253317920977" />
  <meta property="article:author" content="https://www.facebook.com/hassanabidpk89" />
  <meta property="og:description" content="Hassan is a passionate Software Engineer with several years of experience in
  Android,iOS and Web development. He is currently based in Seoul.When he’s not coding, he can be found hiking, running or
  cycling with his smart watch to record all his outdoor activities." />
  <meta property="og:image"content="{% static 'resume/images/hassan_gds.jpg' %}" />
  <meta property="og:url" content="http://hassanabid.com/contact/" />
{% endblock %}
{% block contact-active %}
is-active
 {% endblock %}
{% block content %}
<div class="mdl-grid portfolio-max-width portfolio-contact">
    <div class="mdl-cell mdl-cell--12-col mdl-card mdl-shadow--4dp">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Contact</h2>
        </div>
        <div class="mdl-card__media">
            <img class="article-image" src="{% static 'resume/images/contact-image.jpg' %}" border="0" alt="">
        </div>
        <div class="mdl-card__supporting-text">
            <p>
                If you would like me to review your code, or need help with anything? Don't hestitate to shoot me a message!
            </p>
            <form method="post" id="contact-form" class="">
                {% csrf_token %}
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" pattern="[A-Z,a-z, ]*" type="text" id="full_name" name="full_name">
                    <label class="mdl-textfield__label" for="full_name">Name...</label>
                    <span class="mdl-textfield__error">Letters and spaces only</span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="text" id="email" name="email">
                    <label class="mdl-textfield__label" for="email">Email...</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <textarea class="mdl-textfield__input" type="text" rows="5" id="note" name="note"></textarea>
                    <label class="mdl-textfield__label" for="note">Enter note</label>
                </div>
                <p>
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">
                        Submit
                    </button>
                </p>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block contactjs %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="{% static 'resume/js/script.js' %}"></script>
{% endblock %}